/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import awesomeHelp from "@exfabrica/strapi-plugin-awesome-help/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiAdvancedUuid from "strapi-advanced-uuid/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import reactIcons from "strapi-plugin-react-icons/strapi-admin";
import tagsinput from "strapi-plugin-tagsinput/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "awesome-help": awesomeHelp,
    "strapi-cloud": strapiCloud,
    "color-picker": colorPicker,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-advanced-uuid": strapiAdvancedUuid,
    "multi-select": multiSelect,
    "react-icons": reactIcons,
    tagsinput: tagsinput,
  },
});
